name: niagara-framework
version: '4.7'
summary: Niagara Framework
description: |
  Niagara is a IoT Framework

grade: devel
confinement: devmode
base: core20

architectures:
  - build-on: amd64

parts:
  my-part:
    plugin: nil
