name: niagara-framework
version: '4.7'
summary: Niagara Framework
description: Niagara is a IoT Framework

grade: devel
confinement: devmode
base: core20

architectures:
  - build-on: amd64

parts:
  jre:
    plugin: dump
    source: ./installer/dist/oracle-jre-linux-x64-es.dist
    source-type: zip
    organize:
      '*': jre/
  core:
    plugin: dump
    source: ./installer/dist/nre-core-linux-x64.dist
    source-type: zip
    organize:
      '*': bin/
  config:
    plugin: dump
    source: ./installer/dist/nre-config-linux-x64.dist
    source-type: zip
  modules:
    plugin: dump
    source: ./installer/modules/
    source-type: local
