name: niagara4
version: '4.7'
summary: Niagara Framework
description: Niagara is a IoT Framework

grade: devel
confinement: devmode
base: core18

architectures:
  - build-on: amd64

system-usernames:
  snap_daemon: shared

apps:
  niagarad:
    command: bin/start_niagarad.sh 
    environment:
      LD_LIBRARY_PATH: $SNAP/bin
      HOME: $SNAP_COMMON
  daemon:
    command: bin/start_niagarad.sh /console 
    daemon: simple
    environment:
      LD_LIBRARY_PATH: $SNAP/bin
      HOME: $SNAP_COMMON

parts:
  jre:
    plugin: dump
    source: ./installer/dist/oracle-jre-linux-x64-es.dist
    source-type: zip
    organize:
      '*': jre/
  core:
    plugin: dump
    source: ./installer/dist/nre-core-linux-x64.dist
    source-type: zip
    stage:
      - -ext/jxbrowser    
      - '*'
    organize:
      '*': bin/
  config:
    plugin: dump
    source: ./installer/dist/nre-config-linux-x64.dist
    source-type: zip
    stage-packages:
      - setpriv
    stage:
      - -etc    
      - -*.sh
      - -INSTALL
      - -README
      - -META-INF
      - '*'
    override-prime: |
      snapcraftctl prime
      ln -sf /var/snap/niagara4/common/etc etc
  modules:
    plugin: nil
    override-prime: |
      snapcraftctl prime
      ln -sf /var/snap/niagara4/common/modules modules
  extra:
    plugin: dump
    source: ./extra
    source-type: local

layout:
  /etc/niagara:
    symlink: $SNAP_COMMON/etc
